[package]
name = "openfairdb"
version = "0.3.9"
authors = ["Markus Kohlhase <mail@markus-kohlhase.de>", "slowtec GmbH <post@slowtec.de>"]
license = "AGPL-3.0-or-later"

[dependencies]
# clap 3 is supposed to introduce breaking changes
chrono = "*"
clap = "2"
csv = "*"
diesel = { version = "*", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "*", features = ["sqlite"]  }
dotenv = "*"
env_logger = "*"
fast_chemail = "*"
lazy_static = "*"
log = "*"
pwhash = "*"
quick-error = "*"
quoted_printable = "*"
regex = "*"
rocket = "0.4.0-rc.1"
rocket_contrib = "0.4.0-rc.1"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
toml = "*"
url = "*"
uuid = { version = "*", features = ["v4"] }

[features]
default = ["email"]
email = []
